### ISSUE TITLE
Deleting comments when setup a new game.

### ISSUE THREAD

**Issue by GabrieleBattaglia** [tage64/chess-cli#19]
Hi.
This might be a bug.
1. start a game from scratch
2. add a comment to the start position
3. setup a new position by setup command and answer yes to the warning
The preview comment is still present.

**Comment by tage64** [comment]
I don't consider this to be a bug. The setup command sets up a new starting position for the current game, it doesn't create a new one. To create a new game one may use the `games add` command, (which had some bugs which are fixed for the next release).

I have changed the text in the yes/no question though so that it reads:
> Changing the position will delete all moves in the game  and set the new position as start. Do you want to continue?
